vti_encoding:SR|utf8-nl
vti_syncwith_208.159.3.50\:80:TR|09 Mar 2000 17:49:02 -0000
vti_author:SR|Myung
vti_syncwith_dell\\c\:\\nuestramedicina/copy_of_nuestramedicina:TR|09 Mar 2000 17:49:02 -0000
vti_syncwith_toshiba\\c\:\\nuestramedicina:TR|12 Mar 2000 16:14:15 -0000
vti_syncwith_dell\\c\:\\nuestramedicina:TR|09 Mar 2000 17:49:02 -0000
vti_syncwith_toshiba\\c\:\\nuestramedicina server:TR|12 Mar 2000 16:14:15 -0000
vti_syncwith_toshiba\\c\:\\nuestramedicinaserver:TR|12 Mar 2000 16:14:15 -0000
vti_timelastmodified:TR|04 Feb 2003 21:01:01 -0000
vti_syncwith_dell\\c\:\\copy_of_nuestramedicina:TR|09 Mar 2000 17:49:02 -0000
vti_timecreated:TR|04 Feb 2003 19:33:33 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.7802
vti_syncwith_www.nuestramedicina.com\:80:TR|12 Mar 2000 16:14:15 -0000
vti_cacheddtm:TX|04 Feb 2003 21:01:01 -0000
vti_filesize:IR|114
vti_syncwith_localhost\\c\:\\armonia natural/c\:/armonia natural:TR|04 Feb 2003 21:01:01 -0000
vti_syncwith_localhost\\c\:\\armonia/c\:/armonia:TR|04 Feb 2003 21:01:01 -0000
