vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|04 Feb 2003 21:02:29 -0000
vti_syncwith_dell\\c\:\\copy_of_nuestramedicina:TR|12 Mar 2000 15:48:29 -0000
vti_author:SR|Myung
vti_syncwith_toshiba\\c\:\\nuestramedicina:TR|12 Mar 2000 15:48:29 -0000
vti_syncwith_toshiba\\c\:\\nuestramedicina server:TR|12 Mar 2000 15:48:29 -0000
vti_syncwith_toshiba\\c\:\\nuestramedicinaserver:TR|12 Mar 2000 15:48:29 -0000
vti_timecreated:TR|04 Feb 2003 19:33:46 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.7802
vti_syncwith_www.nuestramedicina.com\:80:TR|12 Mar 2000 15:48:29 -0000
vti_cacheddtm:TX|04 Feb 2003 21:02:29 -0000
vti_filesize:IR|390
vti_syncwith_localhost\\c\:\\armonia natural/c\:/armonia natural:TR|04 Feb 2003 21:02:29 -0000
